### ISSUE TITLE
Add an unsupported script extension list to readme

### ISSUE THREAD

**Issue by weiw11** [MarvNC/mangadex-list-exporter#1]
For anyone using greasemonkey to run user scripts, this script does not work. Using violentmonkey works just fine.
It only executes the following code and stops on greasemonkey:
```
console.log(`Getting page ${i} of ${pages} pages`);
```

@MarvNC can you please add an unsupported script extensions list to the readme to let others know that the extensions lists doesn't work with the script?

**Comment by MarvNC** [comment]
Thanks for bringing this to my attention, I have pushed a fix to this issue in https://github.com/MarvNC/mangadex-list-exporter/commit/afdd8813ba22004af0a924a66d744e83b1f7a8ec. Please let me know if it still has that issue after updating.

**Comment by weiw11** [comment]
That fixed the issue with greasemonkey, thanks!
