### ISSUE TITLE
I get an empty file

### ISSUE THREAD

**Issue by manolito62** [MarvNC/mangadex-list-exporter#3]
I did every step, install script, go to my MDlist, set simple view (by default), and then click export, and get an empty file.

![OigEVse](https://user-images.githubusercontent.com/4824412/104748885-0b3f0880-5707-11eb-8214-1eed01dc3624.png)

![4poWFGQ](https://user-images.githubusercontent.com/4824412/104748905-0ed28f80-5707-11eb-95fb-816c39738ff0.png)

**Comment by MarvNC** [comment]
What browser/userscript manager? What does it show in the console?

**Comment by MarvNC** [comment]
Ah, it seems MangaDex changed something as I'm getting this error too. I'll fix it.

**Comment by MarvNC** [comment]
Should be fixed in https://github.com/MarvNC/mangadex-list-exporter/commit/6db4f7936e382677d901b6a6ffb25f7f6e87b1ce.
