### ISSUE TITLE
When exporting to an XML, you should add a comment linking back to your project's URL in the XML.

### ISSUE THREAD

**Issue by tommai78101** [MarvNC/mangadex-list-exporter#5]
Otherwise, there wouldn't be a way for you share your mangadex list exporter if that bookmark XML data's owner shares the data to their friends, and they have no idea how to get to your exporter.

It's just a suggestion. If that's not necessary, it's fine for now.

**Comment by MarvNC** [comment]
Good idea, done in https://github.com/MarvNC/mangadex-list-exporter/commit/72c5f190de4a5041e08c778cff95dcf506c8650a.
