### ISSUE TITLE
403 Error on fetch followed-manga json

### ISSUE THREAD

**Issue by SethCohen** [MarvNC/mangadex-list-exporter#6]
I had an issue where the fetch on [line 28](https://github.com/MarvNC/mangadex-list-exporter/blob/master/mangadex-list-exporter.user.js#L28) failed with a 403 Forbidden error.  

I was able to fix the issue on my end by modifying the line to be
```js
let json = await fetch(url, {
        credentials: 'include'
      }).then((response) => response.json());
```

**Comment by MarvNC** [comment]
Thanks for the report and the fix, updated in https://github.com/MarvNC/mangadex-list-exporter/commit/bb318c319ae61b5cbe74e9e3ce644096a9ccec20.
